--  Configuration for alr_appimage generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Alr_Appimage_Config is
   pragma Pure;

   Crate_Version : constant String := "0.9.0";
   Crate_Name : constant String := "alr_appimage";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Alr_Appimage_Config;
