# Build using Alire.
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@v2
       - name: Update apt
         if: runner.os == 'Linux'
         run: sudo apt-get update
       - name: Update
         run: alr index --update-all
       - name: Build
         run: alr --non-interactive build
         
  release:
    name: Continuous AppImage
    runs-on: ubuntu-22.04
    steps:    
       - name: Delete 'continuous' release and tag
         uses: dev-drprasad/delete-tag-and-release@v1.0
         with:
           delete_release: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
           tag_name: continuous
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@v2
         with:
            branch: "master"
       - name: Update apt
         run: sudo apt-get update
       - name: Update
         run: alr index --update-all
       - name: Build
         run: alr --non-interactive build
       - name: Build AppImage
         run: bin/alr2appimage --use-version
       - name: Release
         uses: softprops/action-gh-release@v2
         with:
           files: alr2appimage*.AppImage
           prerelease: true
           tag_name: continuous
